#define PIN_STATUS_GREEN 5
#define PIN_STATUS_RED 4

#define PIN_LED_GREEN_DDR DDRD
#define PIN_LED_GREEN_PORT PORTD
#define PIN_LED_GREEN_BIT 3

#define PIN_LED_RED_DDR DDRD
#define PIN_LED_RED_PORT PORTD
#define PIN_LED_RED_BIT 2

#define PIN_BTN_GREEN 6
#define PIN_BTN_RED 7
